[package]
org = "ballerina"
name = "ai_tests"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "ai"
version = "@toml.version@"
repository = "local"

[build-options]
observabilityIncluded = true
