[package]
distribution = "2201.12.0"
org = "ballerina"
name = "ai"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AI/Agent", "Cost/Freemium", "Agent", "AI"]
repository = "https://github.com/ballerina-platform/module-ballerina-ai"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ai-native"
version = "1.0.1"
path = "../native/build/libs/ai-native-1.0.1-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ai-native"
version = "1.0.1"
path = "../native/build/libs/ai-native-1.0.1-SNAPSHOT-tests.jar"
testOnly = true

[[platform.java21.dependency]]
groupId = "dev.langchain4j"
artifactId = "langchain4j"
version = "@langchain4j.version"
path="./lib/langchain4j-@langchain4j.version.jar"

[[platform.java21.dependency]]
groupId = "dev.langchain4j"
artifactId = "langchain4j-core"
version = "@langchain4j.version"
path="./lib/langchain4j-core-@langchain4j.version.jar"

[[platform.java21.dependency]]
groupId = "org.apache.opennlp"
artifactId = "opennlp-tools"
version = "@openNlpTools.version"
path="./lib/opennlp-tools-@openNlpTools.version.jar"
