name: CI

on:
  push:
    branches-ignore:
      - "automated/dependency_version_update"
      - "automated/dependency_version_update_tmp"
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@nightly
              with:
                  args:
                      pack ./ballerina
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
            - name: Ballerina Tests
              uses: ballerina-platform/ballerina-action@nightly
              with:
                  args:
                      test --code-coverage ./ballerina
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  ORG_NAME: ${{ secrets.ORG_NAME }}
                  USER_REPO_NAME: ${{ secrets.REPO_NAME }}
                  ISSUE_ASSIGNEE: ${{ secrets.ASSIGNEE }}
                  RESOURCE_PATH: ${{ secrets.RESOURCE_PATH }}
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
                  GITHUB_TOPIC: ${{ secrets.TOPIC }}
                  GITHUB_SECRET: ${{ secrets.SECRET }}
                  GITHUB_CALLBACK: ${{ secrets.CALLBACK }}
                  GITHUB_USERNAME: ${{ secrets.USERNAME }}
                  
            # Read the ballerina test results
            - name: Read Ballerina Test Results
              id: test_results
              run: |
                content=`cat ./ballerina/target/report/test_results.json`                
                content="${content//'%'/'%25'}"
                content="${content//$'\n'/'%0A'}"
                content="${content//$'\r'/'%0D'}"
                echo "::set-output name=testResultsJson::$content"

            # Print the code coverage information
            - name: Code Coverage
              run: |
                echo "Covered Code Lines : ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}}"
                echo "Total Code Lines : $(expr ${{fromJson(steps.test_results.outputs.testResultsJson).missedLines}} + ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}})"
                echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"

            - name: Alert notifier on failure
              if: failure() && (github.event.action == 'check_connector_for_breaking_changes')
              run: |
                curl -X POST \
                'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                --data-raw '{
                  "event_type": "notify-ballerinax-connector-build-failure",
                  "client_payload": {
                    "repoName": "module-ballerinax-ai.agent",
                    "workflow": "CI"
                  }
                }'
