name: Deployment

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@2201.2.1
        with:
          args:
            pack ./ballerina

      - name: Ballerina Push
        uses: ballerina-platform/ballerina-action/@2201.2.1
        with:
          args:
            push
        env:
          WORKING_DIR: ./ballerina
          JAVA_HOME: /usr/lib/jvm/default-jvm
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}