// Copyright (c) 2023 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ai.observe;

import ballerina/cache;
import ballerina/io;
import ballerina/lang.regexp;
import ballerina/log;
import ballerina/time;

# Execution progress record
type ExecutionProgress record {|
    # Unique identifier for this execution
    string executionId;
    # Question to the agent
    string query;
    # Instruction used by the agent during the execution
    string instruction;
    # Execution history of actions performed so far in the current interaction
    ExecutionStep[] executionSteps = [];
    # Contextual information to be used by the tools during the execution
    Context context;
    # History of previous interactions with the agent, including the latest user query
    ChatMessage[] history;
|};

# Execution step information
public type ExecutionStep record {|
    # Response generated by the LLM
    json|FunctionCall llmResponse;
    # Observations produced by the tool during the execution
    anydata|error observation;
|};

# Execution step information
public type ExecutionResult record {|
    # Tool decided by the LLM during the reasoning
    LlmToolResponse tool;
    # Observations produced by the tool during the execution
    anydata|error observation;
|};

public type ExecutionError record {|
    # Response generated by the LLM
    json llmResponse;
    # Error caused during the execution
    LlmInvalidGenerationError|ToolExecutionError|MemoryError|UnauthorizedError 'error;
    # Observation on the caused error as additional instruction to the LLM
    string observation;
|};

# Tool selected by LLM to be performed by the agent
public type LlmToolResponse record {|
    *FunctionCall;
|};

# Output from executing an action
public type ToolOutput record {|
    # Output value the tool
    anydata|error value;
|};

type ExecutorConfig record {|
    ToolStore toolStore;
    ModelProvider model;
    ToolLoadingStrategy toolLoadingStrategy;
    Credential? agentCredential;
    cache:Cache tokenManager;
    Memory memory;
    boolean stateless;
|};

# An executor to perform step-by-step execution of the agent.
class Executor {
    private boolean isCompleted = false;
    private final string sessionId;
    private final ToolStore toolStore;
    private final ModelProvider model;
    private final ToolLoadingStrategy toolLoadingStrategy;
    private final Credential? agentCredential;
    private final cache:Cache tokenManager;
    private final int maxIter;
    private final boolean verbose;
    private final string? agentId;
    private final ExecutionProgress progress;

    // Execution trace state
    private (ExecutionResult|ExecutionError|Error)[] steps = [];
    private Iteration[] iterations = [];
    private string? answer = ();
    private int currentIter = 0;
    private time:Utc iterationStartTime = time:utcNow();
    private final ChatMessage[] conversationHistory;

    isolated function init(ExecutorConfig config, string sessionId, int maxIter, boolean verbose,
            *ExecutionProgress progress) {
        self.sessionId = sessionId;
        self.toolStore = config.toolStore;
        self.model = config.model;
        self.toolLoadingStrategy = config.toolLoadingStrategy;
        self.agentCredential = config.agentCredential;
        self.tokenManager = config.tokenManager;
        self.maxIter = maxIter;
        self.verbose = verbose;
        self.progress = progress;
        self.conversationHistory = cloneMessages(progress.history);
        self.agentId = self.agentCredential?.id;
    }

    isolated function getProgress() returns ExecutionProgress {
        return self.progress;
    }

    isolated function getExecutionTrace() returns ExecutionTrace {
        FunctionCall[] toolCalls = from ExecutionStep step in self.progress.executionSteps
            let var llmResponse = step.llmResponse
            where llmResponse is FunctionCall
            select llmResponse;
        return {steps: self.steps, iterations: self.iterations, answer: self.answer, toolCalls};
    }

    isolated function reason() returns string|FunctionCall|Error {
        if self.isCompleted {
            log:printError("Task is already completed. No more reasoning is needed.",
                    agentId = self.agentId,
                    executionId = self.progress.executionId
            );
            return error TaskCompletedError("Task is already completed. No more reasoning is needed.");
        }
        log:printDebug("LLM reasoning started",
                agentId = self.agentId,
                executionId = self.progress.executionId,
                sessionId = self.sessionId,
                history = self.progress.executionSteps.toString()
        );
        return selectNextTool(self.progress, self.sessionId, self.toolStore, self.toolLoadingStrategy, self.model);
    }

    isolated function act(FunctionCall|string llmResponse) returns ExecutionResult|ExecutionError|string {
        if llmResponse is string {
            log:printDebug("Parsed LLM response as chat response",
                    agentId = self.agentId,
                    executionId = self.progress.executionId,
                    sessionId = self.sessionId,
                    response = llmResponse
            );
            self.isCompleted = true;
            return llmResponse;
        }

        log:printDebug("Parsed LLM response as tool call",
                agentId = self.agentId,
                executionId = self.progress.executionId,
                sessionId = self.sessionId,
                toolName = llmResponse.name,
                arguments = llmResponse.arguments
        );

        observe:ExecuteToolSpan span = self.createToolSpan(llmResponse);

        [anydata, ExecutionError]? validationFailure = self.validateToolCall(llmResponse, span);
        anydata observation;
        ExecutionResult|ExecutionError executionResult;
        if validationFailure is [anydata, ExecutionError] {
            [observation, executionResult] = validationFailure;
        } else {
            [observation, executionResult] = self.executeTool(llmResponse, span);
        }

        self.recordStep({llmResponse, observation});
        return executionResult;
    }

    # Runs the full execution loop until completion or max iterations.
    #
    # + return - The execution trace containing steps, iterations, answer, and tool calls
    isolated function execute() returns ExecutionTrace {
        while !self.isCompleted {
            string|FunctionCall|Error llmResponse = self.reason();
            ExecutionResult|ExecutionError|string|Error step;
            if llmResponse is Error {
                step = llmResponse;
            } else {
                step = self.act(llmResponse);
            }
            self.recordIteration(step);
        }
        return self.getExecutionTrace();
    }

    private isolated function createToolSpan(FunctionCall llmResponse) returns observe:ExecuteToolSpan {
        string toolName = llmResponse.name;
        observe:ExecuteToolSpan span = observe:createExecuteToolSpan(toolName);
        string? toolCallId = llmResponse.id;
        if toolCallId is string {
            span.addId(toolCallId);
        }
        string? toolDescription = self.toolStore.getToolDescription(toolName);
        if toolDescription is string {
            span.addDescription(toolDescription);
        }
        boolean isMcpTool = self.toolStore.isMcpTool(toolName);
        span.addType(isMcpTool ? observe:EXTENTION : observe:FUNCTION);
        span.addArguments(llmResponse.arguments);
        return span;
    }

    private isolated function validateToolCall(FunctionCall llmResponse, observe:ExecuteToolSpan span)
            returns [anydata, ExecutionError]? {
        string toolName = llmResponse.name;
        boolean isMcpTool = self.toolStore.isMcpTool(toolName);
        ToolNotFoundError|ToolInvalidInputError|TokenAcquisitionError|TokenValidationError?
                validateRes = validateTool(llmResponse, self.agentCredential,
                self.tokenManager, self.progress.context, self.toolStore.tools, isMcpTool);
        if validateRes is Error {
            log:printError("Tool validation failed",
                    agentId = self.agentId,
                    executionId = self.progress.executionId,
                    sessionId = self.sessionId,
                    toolName = toolName,
                    'error = validateRes
            );
            anydata observation;
            ExecutionError executionError;
            if validateRes is ToolNotFoundError|ToolInvalidInputError {
                observation = "Tool extraction failed due to tool validation";
                executionError = {
                    llmResponse,
                    'error: validateRes,
                    observation: observation.toString()
                };
            } else {
                observation = "Tool validation failed while attempting to execute the selected tool: "
                        + validateRes.message();
                executionError = {
                    llmResponse,
                    'error: error UnauthorizedError(
                            string `Tool validation failed: ${validateRes.toString()}`,
                            details = {llmResponse}, cause = validateRes.cause()),
                    observation: observation.toString()
                };
            }
            Error toolExecutionError = error Error(observation.toString(), details = {llmResponse});
            span.close(toolExecutionError);
            return [observation, executionError];
        }
        return;
    }

    private isolated function executeTool(FunctionCall llmResponse, observe:ExecuteToolSpan span)
            returns [anydata, ExecutionResult|ExecutionError] {
        string toolName = llmResponse.name;
        ToolOutput|ToolExecutionError|LlmInvalidGenerationError output = self.toolStore.execute(llmResponse,
                self.progress.context);
        if output is Error {
            anydata observation;
            if output is ToolNotFoundError {
                observation = "Tool is not found. Please check the tool name and retry.";
            } else if output is ToolInvalidInputError {
                observation = "Tool execution failed due to invalid inputs. Retry with correct inputs.";
            } else {
                observation = "Tool execution failed. Retry with correct inputs.";
            }
            observation = string `${observation.toString()} <detail>${output.toString()}</detail>`;
            ExecutionError executionError = {
                llmResponse,
                'error: output,
                observation: observation.toString()
            };
            log:printError("Tool execution resulted in error",
                    agentId = self.agentId,
                    executionId = self.progress.executionId,
                    observation = observation.toString(),
                    sessionId = self.sessionId,
                    toolName = toolName
            );
            Error toolExecutionError = error Error(observation.toString(), details = {llmResponse});
            span.close(toolExecutionError);
            return [observation, executionError];
        }
        anydata|error value = output.value;
        anydata observation = value is error ? value.toString() : value;
        log:printDebug("Tool execution successful",
                agentId = self.agentId,
                executionId = self.progress.executionId,
                sessionId = self.sessionId,
                toolName = toolName
        );
        ExecutionResult executionResult = {
            tool: llmResponse,
            observation: value
        };
        span.addOutput(observation);
        span.close();
        return [observation, executionResult];
    }

    # Appends an execution step to the progress history.
    private isolated function recordStep(ExecutionStep step) {
        self.progress.executionSteps.push(step);
    }

    private isolated function recordIteration(ExecutionResult|ExecutionError|string|Error step) {
        ChatAssistantMessage|ChatFunctionMessage|Error iterationOutput = getOutputOfIteration(step);
        ChatMessage[] iterationHistory = buildCurrentIterationHistory(self.progress, self.conversationHistory);
        if self.verbose {
            verbosePrint(step, self.currentIter);
        }
        if self.currentIter == self.maxIter {
            log:printDebug("Maximum iterations reached without final answer",
                    agentId = self.agentId,
                    executionId = self.progress.executionId,
                    iterations = self.currentIter,
                    stepsCompleted = self.steps.length(),
                    sessionId = self.sessionId
            );
            self.isCompleted = true;
            return;
        }
        if step is ExecutionError && step.'error is UnauthorizedError {
            error err = step.'error;
            log:printDebug("Tool validation failed: ",
                    err,
                    executionId = self.progress.executionId,
                    iteration = self.currentIter,
                    sessionId = self.sessionId
            );
            self.steps.push(step);
            self.iterations.push({
                startTime: self.iterationStartTime,
                endTime: time:utcNow(),
                history: iterationHistory,
                output: iterationOutput
            });
        }
        if step is Error {
            error? cause = step.cause();
            log:printDebug("Error occurred during agent iteration",
                    step,
                    executionId = self.progress.executionId,
                    iteration = self.currentIter,
                    sessionId = self.sessionId,
                    cause = cause !is () ? cause.toString() : "none"
            );
            self.steps.push(step);
            self.iterations.push({
                startTime: self.iterationStartTime,
                endTime: time:utcNow(),
                history: iterationHistory,
                output: iterationOutput
            });
            self.isCompleted = true;
            return;
        }
        if step is string {
            self.answer = step;
            log:printDebug("Final answer generated by agent",
                    agentId = self.agentId,
                    executionId = self.progress.executionId,
                    iteration = self.currentIter,
                    answer = step,
                    sessionId = self.sessionId
            );
            self.iterations.push({
                startTime: self.iterationStartTime,
                endTime: time:utcNow(),
                history: iterationHistory,
                output: iterationOutput
            });
            // isCompleted is already set by act() for string responses
            return;
        }
        self.currentIter += 1;
        log:printDebug("Agent iteration started",
                agentId = self.agentId,
                executionId = self.progress.executionId,
                iteration = self.currentIter,
                maxIterations = self.maxIter,
                stepsCompleted = self.steps.length(),
                sessionId = self.sessionId
        );
        self.steps.push(step);
        self.iterations.push({
            startTime: self.iterationStartTime,
            endTime: time:utcNow(),
            history: iterationHistory,
            output: iterationOutput
        });
        self.iterationStartTime = time:utcNow();
    }
}

isolated function run(ExecutorConfig config, string instruction, string query, int maxIter, boolean verbose,
        string sessionId = DEFAULT_SESSION_ID, Context context = new,
        string executionId = DEFAULT_EXECUTION_ID) returns ExecutionTrace {
    string? agentId = config.agentCredential?.id;
    log:printDebug("Agent execution loop started",
            agentId = agentId,
            executionId = executionId,
            sessionId = sessionId,
            maxIterations = maxIter,
            tools = config.toolStore.tools.toString(),
            isStateless = config.stateless
    );

    [ChatMessage[], ChatSystemMessage, ChatUserMessage] historyResult =
            prepareConversationHistory(config.memory, instruction, query, sessionId, agentId, executionId);
    ChatMessage[] history = historyResult[0];
    ChatSystemMessage systemMessage = historyResult[1];
    ChatUserMessage userMessage = historyResult[2];

    Executor executor = new (config, sessionId, maxIter, verbose,
        progress = {instruction, query, context, executionId, history}
    );
    ExecutionTrace trace = executor.execute();

    commitToMemory(config.memory, config.stateless, sessionId, systemMessage, userMessage,
            executor.getProgress(), trace.answer, agentId);
    return trace;
}

# Retrieves conversation history from memory, updates the system message, and appends the user message.
#
# + memory - Memory store used to retrieve the previous conversation history.
# + instruction - Latest system instruction to be set as the system message.
# + query - Current user query to be appended to the conversation history.
# + sessionId - Unique identifier of the conversation session.
# + agentId - Optional identifier of the agent handling the conversation.
# + executionId - Unique identifier of the current execution.
# + return - A tuple containing the updated conversation history, the system message,
#            and the appended user message.
isolated function prepareConversationHistory(Memory memory, string instruction, string query,
        string sessionId, string? agentId, string executionId)
        returns [ChatMessage[], ChatSystemMessage, ChatUserMessage] {
    ChatMessage[]|MemoryError prevHistory = memory.get(sessionId);
    if prevHistory is MemoryError {
        log:printDebug("Failed to retrieve conversation history from memory",
                prevHistory,
                agentId = agentId,
                executionId = executionId,
                sessionId = sessionId
        );
    }
    ChatMessage[] history = (prevHistory is ChatMessage[]) ? [...prevHistory] : [];
    ChatSystemMessage systemMessage = {role: SYSTEM, content: instruction};
    if history.length() > 0 {
        ChatMessage firstMessage = history[0];
        if firstMessage is ChatSystemMessage && instruction != toString(firstMessage.content) {
            history[0] = systemMessage;
        }
    } else {
        history.unshift(systemMessage);
    }
    ChatUserMessage userMessage = {role: USER, content: query};
    history.push(userMessage);
    return [history, systemMessage, userMessage];
}

isolated function commitToMemory(Memory memory, boolean stateless, string sessionId,
        ChatSystemMessage systemMessage, ChatUserMessage userMessage, ExecutionProgress progress,
        string? answer, string? agentId) {
    ChatMessage[] temporaryMemory = [systemMessage, userMessage];
    ChatMessage[] intermediateFunctionCallMessages = createFunctionCallMessages(progress);
    temporaryMemory.push(...intermediateFunctionCallMessages);
    if answer is string {
        ChatAssistantMessage finalAssistantMessage = {role: ASSISTANT, content: answer};
        temporaryMemory.push(finalAssistantMessage);
    }

    updateMemory(memory, sessionId, temporaryMemory, agentId);
    if stateless {
        MemoryError? err = memory.delete(sessionId);
        // Ignore this error since the stateless agent always relies on DefaultMessageWindowChatMemoryManager,
        // which never return an error.
    }
}

isolated function verbosePrint(ExecutionResult|ExecutionError|Error|string step, int iter) {
    io:println(string `${"\n\n"}Agent Iteration ${iter.toString()}`);
    if step is string {
        io:println(string `${"\n\n"}Final Answer: ${step}${"\n\n"}`);
        return;
    }
    if step is ExecutionResult {
        LlmToolResponse tool = step.tool;
        io:println(string `Action:
    ${BACKTICKS}
    {
        ${ACTION_NAME_KEY}: ${tool.name},
        ${ACTION_ARGUEMENTS_KEY}: ${(tool.arguments ?: "None").toString()}
    }
    ${BACKTICKS}`);

        anydata|error observation = step?.observation;
        if observation is error {
            io:println(string `${OBSERVATION_KEY} (Error): ${observation.toString()}`);
        } else if observation !is () {
            io:println(string `${OBSERVATION_KEY}: ${observation.toString()}`);
        }
        return;
    }
    if step is ExecutionError {
        error? cause = step.'error.cause();
        io:println(string `LLM Generation Error: 
    ${BACKTICKS}
    {
        message: ${step.'error.message()},
        cause: ${(cause is error ? cause.message() : "Unspecified")},
        llmResponse: ${step.llmResponse.toString()}
    }
    ${BACKTICKS}`);
    }
}

isolated function getOutputOfIteration(ExecutionResult|ExecutionError|string|Error step)
    returns ChatAssistantMessage|ChatFunctionMessage|Error {
    if step is Error {
        return step;
    }
    if step is string {
        return {role: ASSISTANT, content: step};
    }
    if step is ExecutionError {
        return step.'error;
    }
    return {
        role: FUNCTION,
        name: step.tool.name,
        id: step.tool.id,
        content: getObservationString(step.observation)
    };
}

isolated function buildCurrentIterationHistory(ExecutionProgress progress,
        ChatMessage[] conversationHistoryUpToCurrentUserQuery) returns ChatMessage[] {
    ChatMessage[] messages = createFunctionCallMessages(progress);
    messages.unshift(...conversationHistoryUpToCurrentUserQuery);
    return messages;
}

isolated function getObservationString(anydata|error observation) returns string {
    if observation is () {
        return "Tool didn't return anything. Probably it is successful. Should we verify using another tool?";
    } else if observation is error {
        record {|string message; string cause?;|} errorInfo = {
            message: observation.message().trim()
        };
        error? cause = observation.cause();
        if cause is error {
            errorInfo.cause = cause.message().trim();
        }
        return "Error occured while trying to execute the tool: " + errorInfo.toString();
    } else {
        return observation.toString().trim();
    }
}

# Get the tools registered with the agent.
#
# + agent - Agent instance
# + return - Array of tools registered with the agent
public isolated function getTools(Agent agent) returns Tool[] => agent.toolStore.tools.toArray();

isolated function updateMemory(Memory memory, string sessionId, ChatMessage[] messages, string? agentId) {
    error? updationStation = memory.update(sessionId, messages);
    if updationStation is error {
        log:printError("Error occured while updating the memory", updationStation, agentId = agentId);
    }
}

isolated function createFunctionCallMessages(ExecutionProgress progress) returns ChatMessage[] {
    ChatMessage[] messages = [];
    foreach ExecutionStep step in progress.executionSteps {
        FunctionCall|error functionCall = step.llmResponse.fromJsonWithType();
        if functionCall is error {
            panic error Error("Badly formated history for function call agent", llmResponse = step.llmResponse);
        }

        messages.push({
            role: ASSISTANT,
            toolCalls: [functionCall]
        },
        {
            role: FUNCTION,
            name: functionCall.name,
            content: getObservationString(step.observation),
            id: functionCall?.id
        });
    }
    return messages;
}

isolated function modifyUserPromptWithToolsInfo(ChatUserMessage chatUserMsg, ToolInfo[] toolInfo)
returns ChatUserMessage {
    string toolsPrompt = string `

These are the tools available to you: 
${BACKTICKS} 
${toolInfo.toJsonString()}
${BACKTICKS}

Select only the tools required to complete the task and return them as a JSON array of tool names:
${BACKTICKS} 
["toolNameOne","toolNameTwo","toolNameN"]
${BACKTICKS}

If no tools are needed, return an empty array:
${BACKTICKS}
[]
${BACKTICKS}`;

    string|Prompt content = chatUserMsg.content;
    if content is string {
        content += toolsPrompt;
    } else {
        content.insertions.push(toolsPrompt);
    }

    return {role: USER, content, name: chatUserMsg.name};
}

isolated function getSelectedToolsFromAssistantMessage(ChatAssistantMessage assistantMsg) returns string[]? {
    do {
        string rawResponse = assistantMsg.content ?: "[]";
        string cleanedJson = regexp:replaceAll(check regexp:fromString("```"), rawResponse, "");
        return check cleanedJson.fromJsonStringWithType();
    } on fail {
        // In case of failure try to load all tools and ignore the error
        return;
    }
}

isolated function cloneMessages(ChatMessage[] messages) returns ChatMessage[] {
    ChatMessage[] clonedMessages = [];
    foreach ChatMessage msg in messages {
        if msg is ChatUserMessage {
            clonedMessages.push(cloneUserMessage(msg));
            continue;
        }
        if msg is ChatSystemMessage {
            clonedMessages.push(cloneSystemMessage(msg));
            continue;
        }
        if msg is ChatAssistantMessage|ChatFunctionMessage {
            clonedMessages.push(msg.clone());
        }
    }
    return clonedMessages;
}

isolated function cloneUserMessage(ChatUserMessage message) returns ChatUserMessage {
    string|Prompt content = message.content;
    string|Prompt clonedContent = content is string ? content
        : createPrompt(content.strings, content.insertions.cloneReadOnly());
    ChatUserMessage clonedMessage = {
        role: USER,
        content: clonedContent
    };
    if message?.name is string {
        clonedMessage.name = message?.name;
    }
    return clonedMessage;
}

isolated function cloneSystemMessage(ChatSystemMessage message) returns ChatSystemMessage {
    string|Prompt content = message.content;
    string|Prompt clonedContent = content is string ? content
        : createPrompt(content.strings, content.insertions.cloneReadOnly());
    ChatSystemMessage clonedMessage = {
        role: SYSTEM,
        content: clonedContent
    };
    if message?.name is string {
        clonedMessage.name = message?.name;
    }
    return clonedMessage;
}

isolated function lazyLoadTools(ChatMessage[] messages, ChatCompletionFunctions[] registeredTools,
        ModelProvider model) returns ChatCompletionFunctions[]? {
    ChatMessage lastMessage = messages[messages.length() - 1];
    if lastMessage !is ChatUserMessage {
        return;
    }
    ToolInfo[] toolInfo = registeredTools.'map(tool => {name: tool.name, description: tool.description});
    ChatUserMessage modifiedUserMessage = modifyUserPromptWithToolsInfo(lastMessage, toolInfo);

    // Replace the last user message with the modified one that includes the tools prompt
    _ = messages.pop();
    messages.push(modifiedUserMessage);

    ChatAssistantMessage|Error response = model->chat(messages, []);
    if response is Error {
        return;
    }

    log:printDebug(string `Calling model for lazy tool loading. Raw response: ${response.content.toString()}`);
    string[]? selectedTools = getSelectedToolsFromAssistantMessage(response);
    log:printDebug(string `Extracted tools from model response: ${selectedTools.toString()}`);

    if selectedTools is string[] {
        // Only load the tool schemas picked by the model
        return from ChatCompletionFunctions tool in registeredTools
            let string toolName = tool.name
            where selectedTools.some(selected => selected == toolName)
            select tool;
    }
    return;
}

isolated function getFirstToolCall(ChatAssistantMessage msg) returns FunctionCall? {
    FunctionCall[]? toolCalls = msg?.toolCalls;
    if toolCalls is () || toolCalls.length() == 0 {
        return;
    }
    return toolCalls[0];
}
