// Copyright (c) 2023 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ai.intelligence;
import ai.observe;

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/jballerina.java;

# Roles for the chat messages.
public enum ROLE {
    SYSTEM = "system",
    USER = "user",
    ASSISTANT = "assistant",
    FUNCTION = "function"
}

# User chat message record.
public type ChatUserMessage record {|
    # Role of the message
    USER role;
    # Content of the message
    string|Prompt content;
    # An optional name for the participant
    # Provides the model information to differentiate between participants of the same role
    string name?;
|};

# System chat message record.
public type ChatSystemMessage record {|
    # Role of the message
    SYSTEM role;
    # Content of the message
    string|Prompt content;
    # An optional name for the participant
    # Provides the model information to differentiate between participants of the same role
    string name?;
|};

# Assistant chat message record.
public type ChatAssistantMessage record {|
    # Role of the message
    ASSISTANT role;
    # The contents of the assistant message
    # Required unless `tool_calls` or `function_call` is specified
    string? content = ();
    # An optional name for the participant
    # Provides the model information to differentiate between participants of the same role
    string name?;
    # The function calls generated by the model, such as function calls
    FunctionCall[]? toolCalls = ();
|};

# Function message record.
public type ChatFunctionMessage record {|
    # Role of the message
    FUNCTION role;
    # Content of the message
    string? content = ();
    # Name of the function when the message is a function call
    string name;
    # Identifier for the tool call
    string id?;
|};

# Chat message record.
public type ChatMessage ChatUserMessage|ChatSystemMessage|ChatAssistantMessage|ChatFunctionMessage;

# Interactive chat messages.
# This is the type `ChatMessage` excluding the type `ChatSystemMessage`.
public type ChatInteractiveMessage ChatUserMessage|ChatAssistantMessage|ChatFunctionMessage;

# Function definitions for function calling API.
public type ChatCompletionFunctions record {|
    # Name of the function
    string name;
    # Description of the function
    string description;
    # Parameters of the function
    map<json> parameters?;
|};

# Function call record
public type FunctionCall record {|
    # Name of the function
    string name;
    # Arguments of the function
    map<json>? arguments = {};
    # Identifier for the tool call
    string id?;
|};

# Raw template type for prompts.
public type Prompt object {
    *object:RawTemplate;
    # The fixed string parts of the template.
    public string[] & readonly strings;
    # The insertions in the template. 
    # Array of values to be inserted into the template, can be anydata, Document, or Chunk types
    public (anydata|Document|Document[]|Chunk|Chunk[])[] insertions;
};

# Projects a `ChatMessageChunk` stream onto its answer text, yielding each non-empty
# `content` fragment and skipping tool-call, reasoning and finish-only chunks. Backs
# `generateAsStream`; closing it closes the underlying chunk stream.
class TextContentIterator {
    private final stream<ChatMessageChunk, Error?> chunks;

    isolated function init(stream<ChatMessageChunk, Error?> chunks) {
        self.chunks = chunks;
    }

    public isolated function next() returns record {|string value;|}|Error? {
        while true {
            record {|ChatMessageChunk value;|}|Error? next = self.chunks.next();
            if next !is record {|ChatMessageChunk value;|} {
                return next;
            }
            string? content = next.value.content;
            if content is string && content.length() > 0 {
                return {value: content};
            }
        }
    }

    public isolated function close() returns Error? {
        return self.chunks.close();
    }
}

# Represents an extendable client for interacting with an AI model.
public type ModelProvider distinct isolated client object {
    # Sends a chat request to the model with the given messages and tools.
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ChatMessage[]|ChatUserMessage messages, ChatCompletionFunctions[] tools = [], string? stop = ())
        returns ChatAssistantMessage|Error;

    # Sends a streaming chat request to the model with the given messages and tools.
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - A stream of assistant message chunks or an error in-case of failures
    isolated remote function chatAsStream(ChatMessage[]|ChatUserMessage messages, ChatCompletionFunctions[] tools = [], string? stop = ())
        returns stream<ChatMessageChunk, Error?>|Error;

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat request
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>) returns td|Error;

    # Sends a streaming chat request to the model using the given prompt and streams
    # back the generated answer as text fragments.
    #
    # Streaming produces text only: structured types have no valid intermediate state, so use
    # `generate` for structured output.
    #
    # + prompt - The prompt to use in the chat request
    # + return - A stream of text fragments, or an error if generation fails
    isolated remote function generateAsStream(Prompt prompt) returns stream<string, Error?>|Error;
};

# Represents configuratations of WSO2 provider.
#
# + serviceUrl - The URL for the WSO2 AI service
# + accessToken - Access token for accessing WSO2 AI service
public type Wso2ProviderConfig record {|
    string serviceUrl;
    string accessToken;
|};

const DEFAULT_TEMPERATURE = 0.7d;
const DEFAULT_GENERATOR_CONFIG = {};

# WSO2 model provider implementation that provides chat completion capabilities using WSO2's AI services.
public isolated distinct client class Wso2ModelProvider {
    *ModelProvider;
    private final intelligence:Client llmClient;
    private final http:Client streamHttpClient;
    private final decimal temperature;
    private final readonly & GeneratorConfig generatorConfig;

    # Initializes a new `WSO2ModelProvider` instance.
    #
    # + serviceUrl - The base URL of WSO2 intelligence API endpoint
    # + accessToken - The access token for authenticating API requests
    # + temperature - The temperature for controlling randomness in the model's output
    # + generatorConfig - Configuration for the `ModelProvider.generate()` method.
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `nil` on success, or an `ai:Error` if initialization fails
    public isolated function init(@display {label: "Service URL"} string serviceUrl,
            @display {label: "Access Token"} string accessToken,
            @display {label: "Temperature"} decimal temperature = DEFAULT_TEMPERATURE,
            @display {label: "Generator Configuration"} readonly & GeneratorConfig generatorConfig = DEFAULT_GENERATOR_CONFIG,
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns Error? {
        intelligence:ConnectionConfig intelligenceConfig = {
            auth: {
                token: accessToken
            },
            httpVersion: connectionConfig.httpVersion,
            http1Settings: connectionConfig.http1Settings,
            http2Settings: connectionConfig.http2Settings,
            timeout: connectionConfig.timeout,
            forwarded: connectionConfig.forwarded,
            poolConfig: connectionConfig.poolConfig,
            cache: connectionConfig.cache,
            compression: connectionConfig.compression,
            circuitBreaker: connectionConfig.circuitBreaker,
            retryConfig: connectionConfig.retryConfig,
            responseLimits: connectionConfig.responseLimits,
            secureSocket: connectionConfig.secureSocket,
            proxy: connectionConfig.proxy,
            validation: connectionConfig.validation
        };
        intelligence:Client|error llmClient = new (config = intelligenceConfig, serviceUrl = serviceUrl);
        if llmClient is error {
            return error Error("Failed to initialize Wso2ModelProvider", llmClient);
        }

        http:ClientConfiguration streamClientConfig = {
            auth: {token: accessToken},
            httpVersion: connectionConfig.httpVersion,
            http1Settings: connectionConfig.http1Settings,
            http2Settings: connectionConfig.http2Settings,
            timeout: connectionConfig.timeout,
            forwarded: connectionConfig.forwarded,
            poolConfig: connectionConfig.poolConfig,
            cache: connectionConfig.cache,
            compression: connectionConfig.compression,
            circuitBreaker: connectionConfig.circuitBreaker,
            retryConfig: connectionConfig.retryConfig,
            responseLimits: connectionConfig.responseLimits,
            secureSocket: connectionConfig.secureSocket,
            proxy: connectionConfig.proxy,
            validation: connectionConfig.validation
        };
        http:Client|error streamHttpClient = new (serviceUrl, streamClientConfig);
        if streamHttpClient is error {
            return error Error("Failed to initialize Wso2ModelProvider", streamHttpClient);
        }

        self.llmClient = llmClient;
        self.streamHttpClient = streamHttpClient;
        self.temperature = temperature;
        self.generatorConfig = generatorConfig;
    }

    # Sends a chat request to the model with the given messages and tools.
    #
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ChatMessage[]|ChatUserMessage messages, ChatCompletionFunctions[] tools, string? stop = ())
    returns ChatAssistantMessage|Error {
        observe:ChatSpan span = observe:createChatSpan("gpt-4o-mini");
        span.addProvider("WSO2");
        if stop is string {
            span.addStopSequence(stop);
        }
        span.addTemperature(self.temperature);
        span.addInputMessages(convertMessageToJson(messages));

        intelligence:CreateChatCompletionRequest request = {
            stop,
            messages: self.mapToChatCompletionRequestMessage(messages),
            temperature: self.temperature
        };
        if tools.length() > 0 {
            request.functions = tools;
            span.addTools(tools);
        }
        intelligence:CreateChatCompletionResponse|error response = self.llmClient->/chat/completions.post(request, headers = {
            "x-product": "bi",
            "x-usage-context": "model_provider_chat"
        });
        if response is error {
            Error err = error LlmConnectionError("Error while connecting to the model", response);
            span.close(err);
            return err;
        }
        if response.choices.length() == 0 {
            Error err = error LlmInvalidResponseError("Empty response from the model when using function call API");
            span.close(err);
            return err;
        }
        intelligence:ChatCompletionResponseMessage? message = response.choices[0].message;

        string|int? responseId = response["id"];
        if responseId is string {
            span.addResponseId(responseId);
        }
        int? inputTokens = response.usage?.promptTokens;
        if inputTokens is int {
            span.addInputTokenCount(inputTokens);
        }
        int? outputTokens = response.usage?.completionTokens;
        if outputTokens is int {
            span.addOutputTokenCount(outputTokens);
        }
        string? finishReason = response.choices[0].finishReason;
        if finishReason is string {
            span.addFinishReason(finishReason);
        }

        ChatAssistantMessage chatAssistantMessage = {role: ASSISTANT, content: message?.content};
        intelligence:ChatCompletionFunctionCall? functionCall = message?.functionCall;
        if functionCall is () {
            span.addOutputMessages(chatAssistantMessage);
            span.close();
            return chatAssistantMessage;
        }
        FunctionCall|Error toolCall = check self.mapToFunctionCall(functionCall);
        if toolCall is Error {
            span.close(toolCall);
            return toolCall;
        }
        chatAssistantMessage.toolCalls = [toolCall];
        span.addOutputType(observe:TEXT);
        span.addOutputMessages(chatAssistantMessage);
        span.close();
        return chatAssistantMessage;
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>) returns td|Error = @java:Method {
        'class: "io.ballerina.stdlib.ai.wso2.Generator"
    } external;

    # Sends a streaming chat request to the model with the given messages and tools.
    #
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - A stream of assistant message chunks or an error in-case of failures
    isolated remote function chatAsStream(ChatMessage[]|ChatUserMessage messages, ChatCompletionFunctions[] tools = [], string? stop = ())
            returns stream<ChatMessageChunk, Error?>|Error {
        observe:ChatSpan span = observe:createChatSpan("gpt-4o-mini");
        span.addProvider("WSO2");
        if stop is string {
            span.addStopSequence(stop);
        }
        span.addTemperature(self.temperature);
        span.addInputMessages(convertMessageToJson(messages));

        intelligence:CreateChatCompletionRequest request = {
            stop,
            messages: self.mapToChatCompletionRequestMessage(messages),
            temperature: self.temperature,
            'stream: true
        };
        if tools.length() > 0 {
            request.functions = tools;
            span.addTools(tools);
        }
        return self.openChunkStream(request, span);
    }

    # Sends a streaming chat request to the model using the given prompt and streams
    # back the generated answer as text fragments. The request is built from the prompt
    # the same way as for `generate` (text and image content parts), without the
    # structured-output tool.
    #
    # + prompt - The prompt to use in the chat request
    # + return - A stream of text fragments, or an error if generation fails
    isolated remote function generateAsStream(Prompt prompt) returns stream<string, Error?>|Error {
        observe:GenerateContentSpan span = observe:createGenerateContentSpan("gpt-4o-mini");
        span.addTemperature(self.temperature);
        span.addProvider("WSO2");

        DocumentContentPart[]|Error content = generateChatCreationContent(prompt);
        if content is Error {
            span.close(content);
            return content;
        }
        intelligence:CreateChatCompletionRequest request = {
            messages: [{role: USER, "content": content}],
            temperature: self.temperature,
            'stream: true
        };
        span.addInputMessages(request.messages.toJson());

        stream<ChatMessageChunk, Error?> chunks = check self.openChunkStream(request, span);
        return new stream<string, Error?>(new TextContentIterator(chunks));
    }

    // Opens the SSE stream for `request`. The span is closed here if the connection fails,
    // and by the returned stream's iterator otherwise.
    private isolated function openChunkStream(intelligence:CreateChatCompletionRequest request, observe:LlmSpan span)
            returns stream<ChatMessageChunk, Error?>|Error {
        Wso2SseEventStream|error sseEvents = self.streamHttpClient->post("/chat/completions", request,
                headers = {"x-product": "bi", "x-usage-context": "model_provider_chat"},
                targetType = Wso2SseEventStream);
        if sseEvents is error {
            Error err = error LlmConnectionError("Error while connecting to the model", sseEvents);
            span.close(err);
            return err;
        }
        return new stream<ChatMessageChunk, Error?>(new Wso2ChatStreamIterator(sseEvents, span));
    }

    private isolated function mapToChatCompletionRequestMessage(ChatMessage[]|ChatUserMessage messages)
    returns intelligence:ChatCompletionRequestMessage[] {
        if messages is ChatUserMessage {
            return [self.mapUserOrSystemMessage(messages)];
        }
        intelligence:ChatCompletionRequestMessage[] chatCompletionRequestMessages = [];
        foreach ChatMessage message in messages {
            if message is ChatAssistantMessage {
                intelligence:ChatCompletionRequestMessage assistantMessage = {role: ASSISTANT};
                FunctionCall[]? toolCalls = message.toolCalls;
                if toolCalls is FunctionCall[] && toolCalls.length() > 0 {
                    assistantMessage["function_call"] = {
                        name: toolCalls[0].name,
                        arguments: toolCalls[0].arguments.toJsonString()
                    };
                }
                if message?.content is string {
                    assistantMessage["content"] = message?.content;
                }
                chatCompletionRequestMessages.push(assistantMessage);
                continue;
            }
            if message is ChatUserMessage|ChatSystemMessage {
                intelligence:ChatCompletionRequestMessage transformedMessage = self.mapUserOrSystemMessage(message);
                if message.name is string {
                    transformedMessage["name"] = message.name;
                }
                chatCompletionRequestMessages.push(transformedMessage);
                continue;
            }
            chatCompletionRequestMessages.push(message);
        }
        return chatCompletionRequestMessages;
    }

    private isolated function mapToFunctionCall(intelligence:ChatCompletionFunctionCall functionCall)
    returns FunctionCall|LlmError {
        do {
            json jsonArgs = check functionCall.arguments.fromJsonString();
            map<json>? arguments = check jsonArgs.cloneWithType();
            return {name: functionCall.name, arguments};
        } on fail error e {
            return error LlmError("Invalid or malformed arguments received in function call response.", e);
        }
    }

    private isolated function mapUserOrSystemMessage(ChatUserMessage|ChatSystemMessage message)
    returns intelligence:ChatCompletionRequestMessage => {
        role: message.role,
        "content": getChatMessageStringContent(message.content)
    };
}

# Named alias for the SSE event stream targetType, since `stream<http:SseEvent, error?>` used
# inline as an expression (e.g. `targetType = stream<http:SseEvent, error?>`) is ambiguous for
# the parser around the trailing `?>`.
type Wso2SseEventStream stream<http:SseEvent, error?>;

# Raw shape of a single SSE `data` payload emitted by the WSO2 intelligence
# `/chat/completions` endpoint when `stream: true` is set, mirroring the OpenAI
# chat-completion-chunk wire format. Kept separate from the public `ChatMessageChunk`
# type since the wire format uses provider-specific/legacy field names (for example,
# `function_call` rather than `tool_calls`).
#
# + id - Unique identifier for the completion; stable across all chunks of one response
# + model - The model that produced the completion
# + choices - The streamed choices for this chunk
# + usage - Token usage statistics; sent as `null` or omitted on all but the final chunk
type Wso2StreamChunk record {
    string id?;
    string model?;
    Wso2StreamChoice[] choices?;
    intelligence:CompletionUsage? usage?;
};

# + index - Index of the choice in the list of choices
# + delta - The incremental message content for this chunk
# + finishReason - Reason the model stopped generating tokens; absent until the final chunk
type Wso2StreamChoice record {
    int index?;
    Wso2StreamDelta delta?;
    @jsondata:Name {value: "finish_reason"}
    string? finishReason?;
};

# + content - The answer text fragment for this chunk
# + functionCall - The function name/arguments fragment, when the model is calling a function
type Wso2StreamDelta record {
    string? content?;
    @jsondata:Name {value: "function_call"}
    Wso2StreamFunctionCall? functionCall?;
};

# + name - Name of the function to call; only sent on the first fragment of the call
# + arguments - Incremental JSON-string fragment of the function arguments
type Wso2StreamFunctionCall record {
    string name?;
    string arguments?;
};

# Maps a raw WSO2 stream chunk onto a `ChatMessageChunk`.
#
# The wire format uses the legacy single `function_call` delta, which has no index or call
# id, so tool-call fragments are emitted at index `0`, with `name` as sent on the first
# fragment and `arguments` passed through as raw JSON-string fragments. The wire format
# has no reasoning field, so `reasoning` is always `()`.
#
# + rawChunk - The raw, provider-specific chunk parsed from an SSE `data` payload
# + return - The mapped chunk, or `()` when the event carries nothing for the caller
# (no choices, the role-only opening delta, or a usage-only event)
isolated function mapWso2StreamChunk(Wso2StreamChunk rawChunk) returns ChatMessageChunk? {
    Wso2StreamChoice[]? choices = rawChunk.choices;
    if choices is () || choices.length() == 0 {
        return ();
    }
    Wso2StreamChoice choice = choices[0];
    Wso2StreamDelta delta = choice.delta ?: {};

    string? content = delta?.content == "" ? () : delta?.content;

    ToolCallChunk[]? toolCalls = ();
    Wso2StreamFunctionCall? functionCall = delta?.functionCall;
    if functionCall is Wso2StreamFunctionCall {
        ToolCallChunk toolCall = {index: 0};
        string? name = functionCall.name;
        if name is string {
            toolCall.name = name;
        }
        string? arguments = functionCall.arguments;
        if arguments is string {
            toolCall.arguments = arguments;
        }
        toolCalls = [toolCall];
    }

    FinishReason? finishReason = mapWso2FinishReason(choice?.finishReason);
    if content is () && toolCalls is () && finishReason is () {
        return ();
    }

    ChatMessageChunk chunk = {role: ASSISTANT, content, toolCalls, finishReason};
    string? id = rawChunk.id;
    if id is string {
        chunk.id = id;
    }
    return chunk;
}

# Normalizes a raw WSO2 `finish_reason` value onto the shared `FinishReason` enum.
# `function_call` (the legacy equivalent of `tool_calls`) is folded into `TOOL_CALLS`;
# unrecognized reasons map to `()` rather than failing the stream.
#
# + reason - The raw `finish_reason` string from the wire, if present
# + return - The normalized `FinishReason`, or `()` if absent/unrecognized
isolated function mapWso2FinishReason(string? reason) returns FinishReason? {
    if reason is () {
        return ();
    }
    match reason {
        "stop" => {
            return STOP;
        }
        "length" => {
            return LENGTH;
        }
        "tool_calls"|"function_call" => {
            return TOOL_CALLS;
        }
        "content_filter" => {
            return CONTENT_FILTER;
        }
        _ => {
            return ();
        }
    }
}

# Iterates the raw SSE event stream backing `Wso2ModelProvider.chatAsStream` and
# `Wso2ModelProvider.generateAsStream`, mapping each event's `data` payload onto a
# `ChatMessageChunk` and skipping events that carry nothing for the caller. The response
# id, token usage and finish reason are reported to the span, which is closed exactly once:
# on the `[DONE]` sentinel, on exhaustion, on the first error, or when the caller closes
# the stream early.
class Wso2ChatStreamIterator {
    private final Wso2SseEventStream events;
    private final observe:LlmSpan span;
    private boolean done = false;

    isolated function init(Wso2SseEventStream events, observe:LlmSpan span) {
        self.events = events;
        self.span = span;
    }

    public isolated function next() returns record {|ChatMessageChunk value;|}|Error? {
        while !self.isDone() {
            record {|http:SseEvent value;|}|error? nextEvent = self.events.next();
            if nextEvent is () {
                self.finish();
                return ();
            }
            if nextEvent is error {
                Error err = error LlmConnectionError("Error while reading streaming response from the model",
                        nextEvent);
                self.finish(err);
                return err;
            }
            string? data = nextEvent.value.data;
            if data is () || data.trim().length() == 0 {
                // Comment-only keep-alive events carry no payload.
                continue;
            }
            if data == "[DONE]" {
                self.finish();
                return ();
            }

            Wso2StreamChunk|error rawChunk = jsondata:parseString(data);
            if rawChunk is error {
                Error err = error LlmInvalidResponseError("Invalid or malformed chunk received from the model",
                        rawChunk);
                self.finish(err);
                return err;
            }
            self.recordObservations(rawChunk);
            ChatMessageChunk? chunk = mapWso2StreamChunk(rawChunk);
            if chunk is ChatMessageChunk {
                return {value: chunk};
            }
        }
        return ();
    }

    public isolated function close() returns Error? {
        self.finish();
        error? err = self.events.close();
        if err is error {
            return error LlmConnectionError("Error while closing the streaming response", err);
        }
    }

    // Reports the response id, token usage and raw finish reason carried by `rawChunk` to the span.
    private isolated function recordObservations(Wso2StreamChunk rawChunk) {
        string? id = rawChunk.id;
        if id is string {
            self.span.addResponseId(id);
        }
        intelligence:CompletionUsage? usage = rawChunk?.usage;
        if usage is intelligence:CompletionUsage {
            self.span.addInputTokenCount(usage.promptTokens);
            self.span.addOutputTokenCount(usage.completionTokens);
        }
        Wso2StreamChoice[]? choices = rawChunk.choices;
        if choices is Wso2StreamChoice[] && choices.length() > 0 {
            string? finishReason = choices[0]?.finishReason;
            if finishReason is string {
                self.span.addFinishReason(finishReason);
                self.span.addOutputType(observe:TEXT);
            }
        }
    }

    private isolated function isDone() returns boolean {
        lock {
            return self.done;
        }
    }

    // Marks the stream as done and closes the span with `err`, unless the stream was already done.
    private isolated function finish(Error? err = ()) {
        lock {
            if self.done {
                return;
            }
            self.done = true;
        }
        self.span.close(err);
    }
}

isolated function convertMessageToJson(ChatMessage[]|ChatMessage messages) returns json {
    if messages is ChatMessage[] {
        return messages.'map(msg => msg is ChatUserMessage|ChatSystemMessage ? convertMessageToJson(msg) : msg);
    }
    if messages is ChatUserMessage|ChatSystemMessage {

    }
    return messages !is ChatUserMessage|ChatSystemMessage ? messages :
        {role: messages.role, content: getChatMessageStringContent(messages.content), name: messages.name};
}
