name: PR Build

on: [ pull_request ]

jobs:
  ballerina-build:
    name: Run Ballerina Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@2201.8.6
        with:
          args:
            build
        env:
          WORKING_DIR: ./ballerina
          JAVA_HOME: /usr/lib/jvm/default-jvm

  ballerina-tests:
    # Run Ballerina tests
    name: Run Ballerina Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Ballerina Tests
        uses: ballerina-platform/ballerina-action@2201.8.6
        with:
          args:
            test --code-coverage
        env:
          WORKING_DIR: ./ballerina
          JAVA_HOME: /usr/lib/jvm/default-jvm
      # Read the ballerina test results
      - name: Read Ballerina Test Results
        id: test_results
        run: |
          content=`cat ./ballerina/target/report/test_results.json`                
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=testResultsJson::$content"
      # Print the code coverage information
      - name: Code Coverage
        run: |
          echo "Covered Code Lines : ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}}"
          echo "Total Code Lines : $(expr ${{fromJson(steps.test_results.outputs.testResultsJson).missedLines}} + ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}})"
          echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"
